### ISSUE TITLE
Option to require screen sharing in addition to web-cam

### ISSUE THREAD

**Issue by chriskorosu** [StudyLions/StudyLion#29]
Currently the bot has a setting that, if turned on, requires users to turn on their web-cam during study sessions, or get kicked.

I think it would be really cool if in addition to that, it would require users to turn on screen sharing (either exclusively or as an alternative to web-cam sharing). This is great for students who do most of their work on the computer, and provides some level of accountability, since people may be able to see when you slack off on Youtube instead of completing your coding tasks, for instance.

**Comment by AriHoresh** [comment]
I think it's a great idea, thank you for the suggestion.
