### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float' when !stats

### ISSUE THREAD

**Issue by alexgrupoprimal** [StudyLions/StudyLion#32]
Hi

We have a bug here, occurs when we type `!stats` and occurs randomly.
![Screenshot_20220715_154505](https://user-images.githubusercontent.com/109387027/179299879-21b6f9e2-35e2-4772-86f9-4c008f39ded3.png)

Works only 2 times from 4 o 5.
If you need more info, can ask me.

Greetings

**Comment by Intery** [comment]
Closing as resolved.
