### ISSUE TITLE
Video_channel role/member ignore system

### ISSUE THREAD

**Issue by pallab-nandi** [StudyLions/StudyLion#38]
Hi! can you add a feature on the bot that it can ignore a specific role or member on video_channel so that the person with role don't get any warning from bot to strictly keep their video on the channel.

**Comment by Intery** [comment]
That is a very reasonable feature request. It will be integrated into the video channel system in the ongoing rewrite, thank you for the suggestion.

**Comment by pallab-nandi** [comment]
May I ask when rewrite will be done or when we get this feature update? If you don't mind.

**Comment by Intery** [comment]
@pallab-nandi This has been implemented in the released rewrite now (`rewrite` branch if you are tracking that). See the `video_exempt` setting in the `/configure video_channels` control panel.
