### ISSUE TITLE
[Req] Daily/Weekly/Monthly Study time/coins Leaderboards

### ISSUE THREAD

**Issue by ShootingKing-AM** [StudyLions/StudyLion#4]
Request for <kbd>!</kbd>command for Daily/Weekly Study time/coins Leaderboards to increase consistency between days, weeks and nurture a small competetive spirit to turn up and follow the schedule.

Thanks in advance.

PS: *Noice* bot

**Comment by AriHoresh** [comment]
Hey!

Thank you for the suggestions. We are working on it and hoping to release it in November. 

Ari.

**Comment by ShootingKing-AM** [comment]
Oh, Okay. Will be waiting, Thankyou !
