### ISSUE TITLE
Todo is not server specifc and dosent reset on day end

### ISSUE THREAD

**Issue by ShootingKing-AM** [StudyLions/StudyLion#5]
Todo is not server specifc - Its showing my server's todo of myself on The Study lions server. And dosent reset on day end - Is this expected behaviour ?

**Comment by Intery** [comment]
Todo not being server specific was intentional (it started as server specific, but it was decided to make the Todo lists global).

Each task expires after 24h, rather than at the day end, as described in the info panel on the `!todo` command.

**Comment by Intery** [comment]
Closing as answered.
